export  const data = [
  {
    id: 1,
    name: 'Amzad Karim',
    rating: 4.8,
    role: 'Frontend Developer',
    rate: '$450/month',
    tags: ['Developer', 'Software'],
    featured: false,
    image: 'https://i.ibb.co/8Hr67Ls/oie-x39-Eu-Cw1-Q6ej.jpg',
  },
  {
    id: 2,
    name: 'Kianna Ble',
    rating: 4.3,
    role: 'Supporter',
    rate: '$200/day',
    tags: ['Recruitment', 'Supporter'],
    featured: false,
    image: 'https://i.ibb.co/XZgsWH00/oie-5k-DDDc3-NHJae.jpg',
  },
  {
    id: 3,
    name: 'Joy Tylor',
    rating: 4.3,
    role: 'UI/UX Design',
    rate: '$250/month',
    tags: ['Software', 'UI/UX Design'],
    featured: false,
    image: 'https://i.ibb.co/84z2HVN9/oie-Snw-Pe-Ne-Iah9l.png',
  },
  {
    id: 4,
    name: 'Salaah-al-mahmud',
    rating: 5.0,
    role: 'Product Manager',
    rate: '$860/month',
    tags: ['Software', 'Supporter'],
    featured: false,
    image: 'https://i.ibb.co/67RYbXQ0/oie-2312921h-EHYWRtf.jpg',
  },
  {
    id: 5,
    name: 'Kristina Kim',
    rating: 5.0,
    role: 'UI/UX Designer',
    rate: '$1000/month',
    tags: ['Developer', 'UI/UX Design'],
    featured: false,
    image: 'https://i.ibb.co/PvY8x9JV/pexels-mikhail-nilov-9304676.jpg',
  },
  {
    id: 6,
    name: 'Thiago Henry',
    rating: 5.0,
    role: 'Software Engineer',
    rate: '$200/hr',
    tags: ['AI Developer', 'Developer'],
    featured: true,
    image: 'https://i.ibb.co/JwHfDfCx/pexels-uiliamnornberg-30767572.jpg',
  },
  {
    id: 7,
    name: 'Linkon R. Emod',
    rating: 4.5,
    role: 'Human Resources',
    rate: '$60/day',
    tags: ['Recruitment', 'Software'],
    featured: true,
    image: 'https://i.ibb.co/sptbdQDq/pexels-jonathanborba-19456424.jpg',
  },
  {
    id: 8,
    name: 'Thomas Shelby',
    rating: 4.0,
    role: 'Designer',
    rate: '$21/hr',
    tags: ['Media Editor', 'UI/UX Design'],
    featured: false,
    image:
      'https://i.ibb.co/QZ32JX3/pexels-lubomir-satko-14868412-12437056.jpg',
  },
];
